{% set name = "webob" %}
{% set version = "1.8.10" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c963a11f307bc3f624fbab9dde737701eae255f32981b7a5486a88db1767c2b
  patches:
    # Backport https://github.com/Pylons/webob/commit/447975fe (py3.14 DEFAULT_BUFFER_SIZE)
    - patches/0001-fix-py314-interrupted-request-test.patch

build:
  skip: true # [py<39]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - wheel
    - setuptools
  run:
    - python
    - legacy-cgi >=2.6 # [py>=313]

test:
  imports:
    - webob
  source_files:
    - tests
  requires:
    - pip
    - pytest >=3.1.0
  commands:
    - pip check
    - pytest -v tests

about:
  home: https://webob.org
  license_file: docs/license.txt
  license: MIT
  license_family: MIT
  summary: 'WSGI request and response object'
  description: |
    WebOb provides objects for HTTP requests and responses. Specifically it
    does this by wrapping the WSGI request environment and response
    status/headers/app_iter(body). The request and response objects provide
    many conveniences for parsing HTTP request and forming HTTP responses. Both
    objects are read/write: as a result, WebOb is also a nice way to create HTTP
    requests and parse HTTP responses.
  doc_url: https://docs.pylonsproject.org/projects/webob
  dev_url: https://github.com/Pylons/webob

extra:
  recipe-maintainers:
    - stuertz
