travis:
  secure:
    BINSTAR_TOKEN: TCpPJ62HEjmSSb9AyvRQPwF7AxdxDrEuDCkv4DtN/p+f0xzUCeqDPaOzHgwppqPUi0Ft5VSYDNRGSNV/2wpvV7KDHuGW5tNStPOWwNlARQh5HwwZCAAViN0T9/w6OhtM1Ge54wN0cvsK14acIppDXVPnlYrt27W/IT5qDJXgnhga8LV8iuR3HxdthecQXs4kokF4DSBtoLczB9xVzuBG9laa0epKgUgES1D2Le1h98r9F3tb9ctcFN4pJjOyBBS2xbCyLw/MiMX5HhLEsDj/FCPjE1ujEhfu2RrfJ7/acDLyY5qOXdQz1Gkd5d8cwSnMyIH+3RxKkshFSiYACDiUuXMYcPT/bcWkWR7u6jldSxSE4GapwjNqWdHVs4d1Xvo34As1m9Ohf9k38d+3UAFJ89ar01cI2HPPUmmIlchWWcrmj2Bnbgk595m3htVUj+Rd7wj25pCqIB/LB+BpcLKHPiGxyIGSPkxwfrYwyqfKs1ppU6Q+SNLAEisHFjjTs1rhGxEnFnB5WDkNwg79ji1lqe5snfMTRG1cd/E0WoajgdqXBD+rInWfg8RVrBCxAe/i8HTX3WirUkncpEWURC9fg8KXhutM7wKw1lQsloZTLujm2as+4rqsFvQ6FTyZCZDSLppHSaLYWw9Z3tRLNzEzBjUfSMh5RdUwSJ92tc0YOW8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
