travis:
  secure:
    BINSTAR_TOKEN: eONdUx06bQo9GDXXZBUVnmyAlSWv8PkfLj/Lr0aeMmdCi+jGAK4fiNcx8+igRQeqBBH6mUrQLePzU7GkNmB+oZFZ/XMlNr0PhqF0jSOC9uULKuK8h07Gmmmw1SintaWuNoP7nCNk0gL2GQKnrkUY4saKQ3ZJemtNV2SGk7QhjSUacFQ9MgBtw4a8SrRjZnK6181zIuFog3t7NdPx438FnWt8a5rrzEWngIm+jilewY9WzkmXfi2X8L9E650eUHhGCtGQLb7KTflF/i9JwKLdtasfdoGRBVURt35xuzOsamtfjDMD2K7F0fiSK/MjRYSoi1jKqp0m50Ga0kcHBOZdabNqtKwE+sthqJUnnhEOM7FUrfTmjkWHXw1rMLhISUI4UL5oaweEK6vampM0Jpma6mmZHVly0Ioxyl3+eFjTw3xdkB2QUuQzgbm4irE59BEXImMoKbW5RFSRIZ2L2Gp2GYLNI4oa0ZbsfVyk+i0dRs+CGWUD2cb0FM9cBKrMekQtDXn+8s7SSSOXPPnfT8MYhDHq7sFKu8zYur/iQHlTx6pcCU1nOT+4A0R80L1BXLs2V7ci56ipMk1CcP5z4rTX/L0572c9JRU2KYHoWlN+9aTIDM5gMit4JY+nyaHK+92foJdieAKOjp1xTRHDDO8IV7NvZ3jrFevTZJWVgVTr0Ik=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
