travis:
  secure:
    BINSTAR_TOKEN: mH0AVX9iMaP4+aCG5HHsKaWhmq1nJelsktDhMFt0DNHv3Vb+OIollY8jnBzAW7F/LHBXqKshbVztlPrDiz8mGV8WfBQqi7W9STuYZpECwfPMANNNGjvQiGUZ5O9+bD1bdQTWVMrWXv6wpb1YN4gQZu6L8bfYloIZRfULiSCZQMbES4KyElPoLPRjUlP2RcYC3MqHcz2neFb/Kr+6ayZKv64AmUEcyteVLS6gz+XqXw6Ya0heodZD/bHAIAmXry6G5nAzBn0KfcRtFSPIEA2LruxtnTswiDX3ESeHzAF6XU3ijtU1nW8PqGo006s6yg4ks8E914rHaTJ1yVUGlxvdLZ4d7bL7uZyTQ4wEe1vxNh9SAKAI7KtiUVvQ8GFFcc9XAjxrKNzHVg4ze8wvZIajNidL4qvnZyPtzYG/WFaDJIJl6quXFu0W5798hFO/dG105hw1Y7NMSPIUNpjMDVWU/g0K7Iduk2mBa6+2TQSaKR9DJo6tvJO0762EfTAQ2sY4A91CCxD1Iej0Fl9rb/5Ve7aJUvbfFrnVjIqZ5zvGrIHj1XCD7Q3/QbLqwM2Ie4LVFSl14QaIQCfglFEG3jqSZbME/bRPvxynmbkKr9IrMxYvB2F0SbK+RQBsyNP1PUspD8SDhl6oHRmmvKzD7Xpbs4YIAoIMuVNFYxZW8Bkahrk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
